[project]
name = "json-to-parquet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.35.1",
]

[tool.uv.workspace]
members = [
    "testluis",
]
